import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import NavbarTop from '@/components/NavbarTop'
import Screen from '@/components/Screen'
import SocialMediaRight from '@/components/SocialMediaRight'
import Head from 'next/head'



export default function Home() {
  return (
    <>
      <Head>
        <title>NetworkAcademy - Thomas M</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className='z-50'><NavbarTop/></div>
      </header>
      <main className=''>
         <div className='sticky top-0 left-0 z-50'><Navbar/></div>
         <div><Screen/></div>
         <div><SocialMediaRight/></div>
      </main>
      <footer>
          <Footer/>
      </footer>
    </>
  )
}
